golang/mock

mockgen/mockgen.go
This is a one line change that fixes #69.
Now when mockgen is invoked with no arguments the usage statement is printed.
=> Added usage statement when called with wrong number of arguments (Fixes #69)

mockgen/mockgen.go
Instead of iterating over a set and generating aliases for conflicting
immports, iterate over a sorted map based on this set. This ensured
predictable output and makes automated checks possible.
We for instance had the problem that our automated check if `go generate` was run, sometimes fails because of different generated code by gomock.
=> Make import alias generation predictable

gomock/call.go, sample/user_test.go
Without this fix, using the `Do` method on a variadic function will cause a panic, because not all of the arguments will be propagated to the action function:
```
$ go test ./sample
--- FAIL: TestVariadicFunction (0.00s)
panic: reflect: Call using zero Value argument [recovered]
panic: reflect: Call using zero Value argument [recovered]
panic: reflect: Call using zero Value argument
...
github.com/golang/mock/gomock.(*Controller).Finish(0xc4200d57a0)
/gopath/src/github.com/golang/mock/gomock/controller.go:149 +0x320
...
github.com/golang/mock/gomock.(*Call).call.func1()
/gopath/src/github.com/golang/mock/gomock/call.go:234 +0x6a
...
FAIL	github.com/golang/mock/sample	0.013s
```
Cc: @iderdik, @chr0n1x
=> Fix Do method for variadic functions

README.md, mockgen/reflect.go
Adds the ability to pass additional flags to `go build`. Fixes #76.
=> Build flags

mockgen/reflect.go
The commit fixes https://github.com/golang/mock/issues/79
=> Pass --buildFlags value to `go build` only when it is not empty

.travis.yml, README.md, check_go_fmt.sh, check_go_generate.sh, gomock/matchers.go, sample/user.go, update_mocks.sh
This change adds a travis-ci (https://travis-ci.org) config that can be used to perform various checks before allowing PRs to be merged into master. This could be a nice addition to the tests written for #81.
The CI setup performs the following checks with several golang versions:
- Sources can be built
- Sources are formatted with `gofmt`
- Generated files are up to date (`go generate ./...`)
- Go tests are passing
The `github.com/golang` account has to sign in to https://travis-ci.org (with github) and after clicking the `<top-right-profile-icon> | Accounts` menu the switch on the left side of the `golang/mock` repo should be turned on.
On github go to the github.com/golang/mock repo, click `Settings | Branches | Protected branches`. Protect the master branch. After protecting it enable …
=> Add travis-ci config

.travis.yml
looking at the travis log, it turns out to be unnecessary.
=> remove install command. 

gomock/call.go, gomock/call_test.go
- Adding a `Call` as its own prerequisite will panic (in `Call.After`)
- Written some tests for `Call.After`
Fixes #84
=> Detect adding 'self' as a prereq in Call.After

gomock/call.go, gomock/callset.go, gomock/controller.go, gomock/controller_test.go
Hi. Thanks for gomock! I just started using it and thought it was not enough verbose when it comes to errors messages.
Before this PR, in my tests, I see an error: `no matching expected call`
```
GOROOT=/usr/local/go
GOPATH=/ide/work
/usr/local/go/bin/go test -c -i -o /tmp/TestHTTP_makeRequestUsingCustomClient_in_http_client_test_gogo 34-mock-http-client-with-gomock
/tmp/TestHTTP_makeRequestUsingCustomClient_in_http_client_test_gogo -test.v -test.run ^TestHTTP_makeRequestUsingCustomClient$
controller.go:129: no matching expected call: *myhttp32.MockHTTPClientInterface.Do([0xc420074b00])
controller.go:174: missing call(s) to *myhttp32.MockHTTPClientInterface.Do(is equal to &{GET some-urla HTTP/1.1 1 1 map[] <nil> <nil> 0 [] false  map[] map[] <nil> map[]   <nil> <nil> <nil> <nil>}) …
```
=> Return verbose errors why expected method call did not match

gomock/call.go, gomock/call_test.go
I needed this while trying to write tests against https://godoc.org/github.com/kidoman/embd#SPIBus
`SPIBus::TransferAndReceiveData([]byte)` writes its output back to the input byte slice.
Would also fix https://github.com/golang/mock/issues/27
=> Support slices in SetArg()

gomock/callset.go
I noticed several tests timing out when attempting to integrate HEAD
into our mainline branch.  The reason was the accidental introduction of
a quadratic call path in callSet.FindMatch, which performed string
concatenation in a tight loop.
This was corroborated by PProf reporting 23 seconds out of 30 seconds
being spent in runtime.concatstrings, which backs onto runtime.memmove.
The host I instrumented this on was not the same as the ones for which
the data is shown below.
The error accumulation routine has been replaced with bytes.Buffer, which
exponentially grows its underlying buffer to amortize the cost.  After
converting a prototype changelist to this pull request you see here, the
total runtime of this test that demonstrated the defect fell from 80
seconds to 15.  This was just one …
=> gomock: fix matcher's degenerate quadratic path.

gomock/callset.go
While writing tests for a stateful object, I noticed unexpected behavior
where the mock would use the 1st call, but then the 3rd expected call
before the 2nd (called in [1,3,2]).
Since our tests all used the `gomock.Any()` function param, there was no
ordering that could be detected by the matching without chaining all
calls with `After()`.
=> retain ordering of expected calls

gomock/call.go, gomock/callset_test.go
Adds tests to complement the changes introduced in #107.
I validated that these tests would have caught the ordering bug fixed by
PR #107 by reverting the change locally:
revert diff:
```diff
diff --git a/gomock/callset.go b/gomock/callset.go
index 05d6fa2..c652f42 100644
--- a/gomock/callset.go
+++ b/gomock/callset.go
@@ -44,7 +44,11 @@ func (cs callSet) Remove(call *Call) {
for i, c := range sl {
if c == call {
// maintain order for remaining calls
-                       methodMap[call.method] = append(sl[:i], sl[i+1:]...)
+                       // methodMap[call.method] = append(sl[:i], sl[i+1:]...)
+                       if len(sl) > 1 {
+                               sl[i] = sl[len(sl)-1]
+                       }
+                       methodMap[call.method] = sl[:len(sl)-1] …
```
=> add tests for callSet Add & Remove

gomock/call.go, gomock/call_test.go, gomock/controller.go
Use Go 1.9's new "testing.T".Helper method to mark gomock's functions as
test helpers so that test failures print the caller's line and file
information instead of gomock's information.
=> mark gomock functions as test helpers

gomock/call.go, gomock/call_test.go, gomock/controller.go, gomock/controller_test.go
Add DoAndReturn as a complement to Do that does not ignore its return values.
Refactored how all the call actions work to make this easier.
Fixes #34
=> Add DoAndReturn

gomock/call.go, gomock/callset.go, gomock/callset_test.go, gomock/controller.go, gomock/controller_test.go
Add a useful error message for when a call to the mock doesn't match any expected calls because they have been exhausted.
Some refactoring is included in order to make the tests easier to write.
Fixes #128
=> Better error message

gomock/call.go, gomock/controller_test.go
This breaks varargs matching a slice that has only one element. I had to remove the test case for this.
Fixes https://github.com/golang/mock/issues/130
=> Fix panic during varargs matching

mockgen/model/model.go, mockgen/reflect.go, mockgen/tests/vendor_pkg/README.md, mockgen/tests/vendor_pkg/doc.go, mockgen/tests/vendor_pkg/vendor/a/a.go
=> Make mockgen mock dependencies in vendor dir

mockgen/tests/aux_imports_embedded_interface/bugreport.go, mockgen/tests/aux_imports_embedded_interface/bugreport_mock.go, mockgen/tests/aux_imports_embedded_interface/faux/faux.go
- `aux` is not a valid directory name on windows
- Fixes https://github.com/golang/mock/pull/134#issuecomment-349758272
=> Rename aux -> faux

gomock/controller.go, gomock/controller_test.go
Failing with `t.Fatal` in case of multiple `Finish` calls on the same controller instance.
This would prevent sharing the same controller between subtests.
=> Fatal on duplicate Controller.Finish call

gomock/matchers.go, gomock/matchers_test.go
This is the exact same idea as https://github.com/golang/mock/pull/132 from @josh-tepper, because I forgot to check for an existing PR for this feature before writing the code (!). But then I took some of the ideas from that PR and merged them with my code to create this PR, which has unit tests and documentation. So this should be a considered a team effort from @josh-tepper and me.
This is very useful when mocking functions that take `interface{}` parameters.
For example, let's say I need to have a mock for this interface:
```go
type Inserter interface {
Insert(list ...interface{}) error
}
```
Using this matcher lets me take:
```go
dbMock.EXPECT().
Insert(gomock.Any()).
Return(errors.New("DB error"))
```
and change it go:
```go
dbMock.EXPECT(). …
```
=> New matcher: gomock.AssignableToTypeOf

mockgen/mockgen.go
When the path does not exist an unnecessary failure is generated. Creating the
directories required is harmless and simplifies generation.
=> Create the path at which mock will be generated

sample/README.md
update_mock.sh script was deleted in 2f85419.
Fixes #142.
=> fix outdated reference to update_mock.sh script

gomock/call.go, gomock/controller.go, gomock/controller_test.go, gomock/internal/mock_matcher/mock_matcher.go, mockgen/internal/tests/aux_imports_embedded_interface/bugreport_mock.go, mockgen/internal/tests/custom_package_name/greeter/greeter_mock_test.go, mockgen/internal/tests/dot_imports/mock.go, mockgen/internal/tests/generated_identifier_conflict/bugreport_mock.go, mockgen/internal/tests/import_source/definition/source_mock.go, mockgen/internal/tests/import_source/source_mock.go, mockgen/internal/tests/internal_pkg/subdir/internal/pkg/reflect_output/mock.go, mockgen/internal/tests/internal_pkg/subdir/internal/pkg/source_output/mock.go, mockgen/internal/tests/unexported_method/bugreport_mock.go, mockgen/internal/tests/vendor_dep/mock.go, mockgen/internal/tests/vendor_dep/source_mock_package/mock.go, mockgen/internal/tests/vendor_pkg/mock.go, mockgen/mockgen.go, mockgen/mockgen_test.go, sample/concurrent/mock/concurrent_mock.go, sample/mock_user/mock_user.go
=> Test helper in mock

mockgen/reflect.go
Previously the temp directory was deleted via a defer, however the error
message was ignored.
=> mockgen: log error while deleting temp directory

mockgen/model/model.go, mockgen/model/model_test.go
This PR changes the search string of a vendor package's import path from `/vendor/` to  `vendor/` so that packages inside `$GOPATH/src/vendor` are properly imported in the generated mocks.
The reasoning is that `t.PkgPath()` for package `$GOPATH/src/vendor/foo` is `vendor/foo` while current code only checks against `/vendor/`, which does not cover the packages inside `$GOPATH/src/vendor`.
This PR fixes https://github.com/golang/mock/issues/276.
=> Fix import path for packages inside $GOPATH/src/vendor

.travis.yml
Go only supports 1.11 and 1.12 at this point. Is it necessary to maintain 1.10?
=> remove go 1.10 support

.travis.yml, ci/check_go_mod.sh
This should help prevent #289 for future commits.
=> ci: adds check to ensure go modules are up to date

mockgen/parse.go
Sometimes mockgen needs to execute from outside Go modules. For example in [bazel_gomock](https://github.com/jmhodges/bazel_gomock) rule, mockgen is executed from the root of a Bazel repository, which may not be in any Go modules. `bazel_gomock` recently removed GOPATH from its runtime (https://github.com/jmhodges/bazel_gomock/pull/16), so GOPATH isn't available either. This PR sets the working directory of `packages.Load` to the source directory, which is guaranteed to be in a Go module or GOPATH.
This PR also decrease the load mode to `packages.LoadFiles` so it's faster and more resilient to errors that shouldn't affect mockgen.
=> Allow mockgen to execute from outside Go modules

mockgen/mockgen.go, mockgen/parse.go
- Replaced range loops with an append
- No need to specify slice capacity that's equal to the length
=> Simplified Go code

gomock/call.go, gomock/controller_test.go
Updated the documentation to something I think seems to be clearer. Also added two tests for this.
=> Update documentation on MinTimes and MaxTimes. Closes #331

.goreleaser.yml
[GoReleaser](https://goreleaser.com) provides an easy way to automate releases via a single config YAML. You can see what the result would look like on my [fork's releases](https://github.com/scevallos/mock/releases). The maintainers of this repo would have to generate a valid GitHub Token and set it as an envvar as specified [here](https://goreleaser.com/environment/). This step can also be [integrated with Travis](https://goreleaser.com/ci/), if the maintainers want to do that.
=> Resolves #147 - Including binaries with tagged releases via GoReleaser

mockgen/reflect.go
Value of -build_flags was passed to 'go' as a single argument.
For example when passing -build_flags "-mod vendor", the invoked
commandline was `go -mod\ vendor` and the go command errored out because
there is no such arg.
That has caused confusion, e.g. in #296
Solve this by splitting the argument by a space.
=> Pass -build_flags as Multiple Args

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Add template for Pull requests, one for bug report issues, and one for feature request issues
=> #358 add template for PR and bug report

gomock/matchers.go, gomock/matchers_test.go
This matcher is to be used to combine multiple matchers into one
statement. Implementation inspired by #189.
=> add All matcher

gomock/matchers.go, gomock/matchers_test.go
This matcher will check the length with any type that allows this
behavior via reflection. Implementation inspired by #189.
=> add Len matcher

gomock/matchers.go, gomock/matchers_test.go
use case:
```go
package main
import (
"context"
"fmt"
"reflect"
"github.com/golang/mock/gomock"
)
func main() {
ctx, cancel := context.WithCancel(context.Background())
defer cancel()
res := gomock.AssignableToTypeOf(context.Background()).Matches(ctx)
fmt.Println(res) // fasle, but I want true!!
ctxType := reflect.TypeOf((*context.Context)(nil)).Elem()
res = gomock.AssignableToTypeOf(ctxType).Matches(ctx)
fmt.Println(res) // true
res = gomock.AssignableToTypeOf(ctxType).Matches(context.Background())
fmt.Println(res) // true
}
```
=> Allow AssignableToTypeOf reflect.Type

mockgen/internal/tests/performance/big_interface/big_interface.go, mockgen/parse_test.go
Add a basic benchmark test for `mockgen` `parseFile` so we can compare performance changes between versions.
review them:
=> add benchmark for parse file

mockgen/mockgen.go, mockgen/mockgen_test.go
=> fix generates non-compilable code

mockgen/mockgen.go, mockgen/model/model.go, mockgen/parse.go
Fixes #380
Fixes #381
Fixes #382
=> fix: avoid constructing improper import graph

mockgen/mockgen.go, mockgen/mockgen_test.go, mockgen/parse.go, mockgen/parse_test.go, mockgen/reflect.go
The reflect method should be renamed so it does not collide with
the reflect package name. As is, it makes import reflect in the
code non-idiomatic. Also renamed sourceMode to stay consistent.
Noticed this here: #371
=> refactor method names for reflect/source

README.md, mockgen/mockgen.go, mockgen/version.1.11.go, mockgen/version.1.12.go
Add -version flag that shows a version provided by Go modules.
This strategy works well for module aware invocations of `go get` and `go
run` (which means using GO111MODULE=on).
If we ever plan to distribute built binaries, it is necessary to amend
the strategy with build flags.
GOPATH mode versioning is unsupported.
=> Add Mockgen Version Flag

go.mod, go.sum, mockgen/internal/tests/custom_package_name/greeter/greeter_mock_test.go, mockgen/internal/tests/import_source/source_mock.go, mockgen/mockgen.go, mockgen/mockgen_test.go, mockgen/parse.go, sample/mock_user/mock_user.go, tools.go
This change now makes use of go list to check for package names. This
tool is module aware and allows for better named imports.
To test this change I needed to also add a small package to our mod
file. To keep this import from disappearing from go.mod I made use
of the tools file strategy.
Note this change will change the import names in generated code. This
should not be a breaking change in user code.
Fixes #326
=> fix not resolving go module major versions

README.md, mockgen/mockgen.go, mockgen/parse.go
I use `go:generate` in my source code to invoke `mockgen` to generate mocked interfaces.
e.g.
```go
//go:generate mockgen -destination=mocks/foo.pb.go github.com/xxx/xxx/pkg/xxx Foo
```
But it's too annoying that every time I have to write and check the package name (github.com/xxx/xxx/pkg/xxx).
And add the full package name in a source file is kind of duplicated information since *golang* could parse the file path and get the package name.
So I add a feature that can use "." to refer to the current path's package.
e.g.
```go
//go:generate mockgen -destination=mocks/foo.pb.go . Foo
```
Just a single `.`, no more `github.com/xxx/xxx/pkg/xxx`.
```
Use "." to refer to the current path's package in reflect mode
```
=> Use "." to refer to the current path's package in reflect mode

mockgen/reflect.go
Fixes #354
Reflect in Current Directory First
Some users have intention to run mockgen in a module aware directory with
version pinned to those in `go.mod`.
Always try to run reflect program in current working directory first.
More context about the root cause of the bug is in https://github.com/golang/mock/issues/354#issuecomment-577147113
=> Reflect in Current Directory First

.goreleaser.yml, mockgen/mockgen.go, mockgen/version.1.11.go, mockgen/version.1.12.go
Fixes #389.
When publishing binaries using Goreleaser use build flags.
Also remove custom archives and checksum name_templates because
Goreleaser has reasonable defaults, see https://goreleaser.com/customization/#Archive
review them:
Describe any changes here so maintainer can include it in the release notes, or delete this block.
```
Examples of user facing changes:
- Improved API for custom matchers
```
=> Goreleaser

mockgen/mockgen.go, mockgen/mockgen_test.go, mockgen/parse.go
Fixes #396. This PR optimise resolving correct package name with `go list` command. Instead of calling `go list` for each import in file, now we do it for all imports in one call.
Time consuming by mockgen:
Source mode
```
(v1.4.0)
time ../mockgen -source user.go -destination mock_user/mock_user.go Index,Embed,Embedded
../mockgen -source user.go -destination mock_user/mock_user.go   2.09s user 2.83s system 280% cpu 1.756 total
(with optimizations)
time ../mockgen -source user.go -destination mock_user/mock_user.go Index,Embed,Embedded
../mockgen -source user.go -destination mock_user/mock_user.go   0.54s user 0.63s system 320% cpu 0.364 total
```
Reflection mode
```
(v1.4.0)
time ../mockgen -destination mock_user/mock_user.go github.com/golang/mock/sample Index,Embed,Embedded
../mockgen …
```
=> Improve performance of mock generation (#396)

gomock/call.go, gomock/call_test.go, gomock/controller_test.go, gomock/internal/validate/validate.go
Fixes #71 
Update the error handling for Call.Do and Call.DoAndReturn in the case where
the argument passed does not match expectations.
* panic if the argument is not a function
* panic if the number of input arguments do not match those expected by Call
* panic if the types of the input arguments do not match those expected
by Call
Call.DoAndReturn has additional validations on the return signature
* panic if the number of return arguments do not match those expected by
Call
* panic if the types of return arguments do not match those expected by
Call
review them:
Describe any changes here so maintainer can include it in the release …
=> Fix #71 Do signature change error msg

mockgen/reflect.go
Fixes: #411 
I am running into an issue when using `mockgen`'s `-prog_only` flag where an empty file is returned, but the program still exits with 0. I suspect this is because `os.Stdout.Write`'s error is being ignored.
n/a
=> mockgen: don't ignore stdout.Write error

gomock/internal/mock_gomock/mock_matcher.go, mockgen/internal/tests/aux_imports_embedded_interface/bugreport_mock.go, mockgen/internal/tests/copyright_file/mock.go, mockgen/internal/tests/custom_package_name/greeter/greeter_mock_test.go, mockgen/internal/tests/dot_imports/mock.go, mockgen/internal/tests/empty_interface/mock.go, mockgen/internal/tests/generated_identifier_conflict/bugreport_mock.go, mockgen/internal/tests/import_source/definition/source_mock.go, mockgen/internal/tests/import_source/source_mock.go, mockgen/internal/tests/internal_pkg/subdir/internal/pkg/reflect_output/mock.go, mockgen/internal/tests/internal_pkg/subdir/internal/pkg/source_output/mock.go, mockgen/internal/tests/mock_in_test_package/mock_test.go, mockgen/internal/tests/self_package/mock.go, mockgen/internal/tests/test_package/mock_test.go, mockgen/internal/tests/unexported_method/bugreport_mock.go, mockgen/internal/tests/vendor_dep/mock.go, mockgen/internal/tests/vendor_dep/source_mock_package/mock.go, mockgen/internal/tests/vendor_pkg/mock.go, mockgen/mockgen.go, sample/concurrent/mock/concurrent_mock.go, sample/mock_user/mock_user.go
Added a period to the end of all declaration comments according to [Go Code Review Comments](https://github.com/golang/go/wiki/CodeReviewComments#comment-sentences):
> Comments should begin with the name of the thing being described and end in a period
Actual code changes are only in ` mockgen/mockgen.go`. Other changes are just tests.
review them:
```
- Added period to the end of generated comments.
```
=> Add a period to the end of comments

mockgen/parse.go
`packages.LoadFiles` is [deprecated](https://pkg.go.dev/golang.org/x/tools/go/packages?tab=doc#pkg-constants). It is not future-proof to use it. In addition, I found all mockgen need is `Package.PkgPath`, so `packages.NeedName` is sufficient.
review them:
=> Using pacakges.NeedName

.travis.yml, README.md, gomock/controller.go, gomock/controller_113_test.go, gomock/controller_114_test.go, gomock/controller_test.go
In go1.14 the testing package added a new cleanup method that is
called at the end of test runs. By taping into this gomock can
remove the need for users to call ctrl.Finish() if they pass a
*testing.T into gomock.NewController(...).
Fixes #407
=> add default calling of ctrl.Finish() in go1.14+

mockgen/parse.go, mockgen/parse_test.go
=> support multi-path gopath

gomock/call.go, gomock/controller.go
In 832173191abead7f0878d8bb24f32f1a5fdf6d79, the callerInfo call
gets nested within an additional function call, but the frame skip
isn't updated. When used with mockgen, this causes the location frame
to unhelpfully point to the generated mock instead of the callsite in
the user's test.
Before:
```
... at .../mocks/mock_ecriface/mock_ECRAPI.go:612 because: there are no expected calls of...
```
After:
```
... at .../example_test.go:29 because: there are no expected calls of...
```
review them:
Describe any changes here so maintainer can include it in the release notes, or delete this block.
```
- Fixes blame location for unexpected …
```
=> gomock/controller: use skip additional frame

gomock/matchers.go
To make the example work we need to include the element to be casted
Fixes https://github.com/golang/mock/issues/453. _in case of a bug fix, this should point to a bug and any other related issue(s)_
The example included in the documentation doesn't work. This PR fixes the documentation
to help other people that want to use it to learn how `AssignableToTypeOf` can be used.
review them:
Describe any changes here so maintainer can include it in the release notes, or delete this block.
=> fix docs for AssignableToTypeOf

mockgen/internal/tests/aux_imports_embedded_interface/bugreport_mock.go, mockgen/internal/tests/aux_imports_embedded_interface/faux/faux.go, mockgen/internal/tests/import_embedded_interface/bugreport.go, mockgen/internal/tests/import_embedded_interface/bugreport_mock.go, mockgen/model/model.go, mockgen/parse.go
example: 
new a interface:  
```go
type NotFound interface {
error
NotFound()
}
```
execute `mockgen -source xxx.go`
=> support embedded error interface in source mode

gomock/call.go, gomock/controller_test.go
Fixes #432 and #391. 
If the matcher implements the `GotFormatter` interface, then call it in order to format the gotten arguments when printing a matching failure. 
review them:
```
- Matchers implementing the GotFormatter interface are no longer ignored. Match failures are formatted correctly. 
```
=> Format variadic arguments with GotFormatter

gomock/internal/mock_gomock/mock_matcher.go, mockgen/internal/tests/aux_imports_embedded_interface/bugreport_mock.go, mockgen/internal/tests/custom_package_name/greeter/greeter_mock_test.go, mockgen/internal/tests/dot_imports/mock.go, mockgen/internal/tests/generated_identifier_conflict/bugreport_mock.go, mockgen/internal/tests/import_embedded_interface/bugreport_mock.go, mockgen/internal/tests/import_embedded_interface/net_mock.go, mockgen/internal/tests/import_source/definition/source_mock.go, mockgen/internal/tests/import_source/source_mock.go, mockgen/internal/tests/internal_pkg/subdir/internal/pkg/reflect_output/mock.go, mockgen/internal/tests/internal_pkg/subdir/internal/pkg/source_output/mock.go, mockgen/internal/tests/mock_in_test_package/mock_test.go, mockgen/internal/tests/self_package/mock.go, mockgen/internal/tests/test_package/mock_test.go, mockgen/internal/tests/unexported_method/bugreport_mock.go, mockgen/internal/tests/vendor_dep/mock.go, mockgen/internal/tests/vendor_dep/source_mock_package/mock.go, mockgen/internal/tests/vendor_pkg/mock.go, mockgen/mockgen.go, sample/concurrent/mock/concurrent_mock.go, sample/mock_user/mock_user.go
Fixes #393
This PR changes mockgen to generate files that are `goimports`-formatted.
The actual change is in `mockgen/mockgen.go`, the other changes are generated.
review them:
Describe any changes here so maintainer can include it in the release notes, or delete this block.
```
- Format generated files with goimports
```
=> Format generated files with goimports

README.md
=> fix readme docs on removing Finish calls

mockgen/parse_test.go
Found some missing error checks for the `os.SetEnv()` method in `mockgen/parse_test.go`.
review them:
/
Fixes: #473
=> check error for os.Setenv in parse_test.go

gomock/matchers.go, gomock/matchers_test.go
Solution to https://github.com/golang/mock/issues/429. Adds support for assignable types to `Eq` matcher.
=> MOCK-429: add support for assignable types to Eq matcher

README.md
As a newbie in the tooling I was not able to find out that there are two modes of generation (Source and Reflect) from first glance. I believe that this small change can help the other like me.
review them:
N/A - no release changes, only markdown changes
=> Separate Readme sections for Source mode, Reflect mode and Flags

mockgen/internal/tests/aux_imports_embedded_interface/bugreport_mock.go, mockgen/internal/tests/import_embedded_interface/bugreport_mock.go, mockgen/internal/tests/mock_in_test_package/mock_test.go, mockgen/internal/tests/test_package/mock_test.go, mockgen/mockgen.go
Fixes #499.
Sorting the methods by name will make sure that their order is consistent in source and reflect mode.
review them:
Updated the tests, but not sure how to test this without writing a parser for the generated mock files.
=> sort methods on the mock implementation alphabetically

mockgen/mockgen_test.go
In Go 1.15 go list will return an error if any of the packages
passed to it are not valid. This differs from pervious behavior
where all of the successful results would be returned. In practice
this should not be an issue as code should contain resolvable
import paths, but this made the test fail.
=> fix Test_createPackageMap for 1.15

README.md
=> add docs on 1.16 install and adding to PATH

sample/user_test.go
test(sample/user_test.go): minor correction at t.Errorf: format
=> test(sample/user_test.go): minor correction at t.Errorf

mockgen/parse.go
Hi team.
fixed error message becasue error strings should not be capitalized.
https://github.com/golang/go/wiki/CodeReviewComments#error-strings
> Error strings should not be capitalized (unless beginning with proper nouns or acronyms) or end with punctuation, since they are usually printed following other context. That is, use fmt.Errorf("something bad") not fmt.Errorf("Something bad"), so that log.Printf("Reading %s: %v", filename, err) formats without a spurious capital letter mid-message. This does not apply to logging, which is implicitly line-oriented and not combined inside other messages.
=> fix error message in parse.go

mockgen/mockgen.go
I know we need output package path to avoid self-importing. However, this only happens when the mock is output into an already existing package, in which case the caller is responsible for passing `-self_package`. Without `-self_package`, guessing output package path should be on best effort basis. There is no requirement for `destination` to be in a Go module or `GOPATH` (in fact, it's hard, if possible at all, to do so in Bazel). So `parsePackageImport(dstPath)` often fails. Such failure should not fail the main program. We should instead be optimistic and leave output package package empty, assuming no self importing would happen.
=> Best effort guesses for output package path

README.md
Hi team.
This PR adds some flags to README.
Why is there no mention in the README about some of the flags? If there is a reason, please let me know.
Thanks
=> add flags documentation

gomock/controller.go
In addition to the description in NewController function's docs, it would be nice if there was a statement in Finish function's docs that there is no need to call Finish() under specific circumstances.
=> Add statement in Finish function about there is no need to call Finish() 

gomock/call.go, gomock/call_test.go
Previous behavior was a panic would happen if the number of args
did not match. Now the test should fail more gracefully and allow
for better debugging.
Fixes: #71
=> feat validate Do & DoReturn args

gomock/call.go, gomock/controller_test.go, gomock/matchers.go
- Adds type information to the default got formatter.
- Adds type to default want formatter. This happens to be
gomock.Eq. Adding more information for debugging seems like a
good idea in this case as well.
Fixes: #190
=> add type information to error messages

gomock/callset.go, gomock/controller_test.go
If [fmt](https://pkg.go.dev/fmt)-verb strings such as `%s` is included in the error message, the output becomes `%!s(MISSING)` unintendedly.
This pull request fixes this problem.
=> fix ill-formatted message with fmt-verbs like %s

README.md, mockgen/reflect.go
=> add notes and error helper for vendor+reflect error

mockgen/internal/tests/const_array_length/input.go, mockgen/internal/tests/const_array_length/mock.go, mockgen/parse.go, mockgen/parse_test.go
Fixes #561 - Panic on array parsing if length is externally defined 
It also fixes the following minor problems in `TestParseArrayWithConstLength`, a test function related to this feature.
- It doesn't check all outputs to be asserted.
- It doesn't initialize some of the fields in `mockgen.fileParser`, even though they are initialized in the production code. (Actually, it caused an unnecessary test error by test data I added)
=> fix parse array with the external const correctly

gomock/call.go, gomock/example_test.go
Regardless of the result of #558, this is not a new requirement (I believe), and the location of it in the example code was easy to miss.
The `Do` version excludes a reference to the output argument count, as the returns are ignored.
=> Move argument requirements for Do and DoAndReturn out of example code and into function commentary

mockgen/reflect.go
Hi. Sorry for very minor change. 😢
The link on error message was not clear because there was no line break, so this PR fixes it.
Some IDE shows link like this. (This pic is GoLand) 
This may confuse users.
=> add line break in for reflect vendoring error

gomock/call.go, gomock/controller_test.go
Solve this issue: https://github.com/golang/mock/issues/588
Solution: Remove all element in the original map and copy the new key/value into it.
=> feat: support SetArg for map argument

mockgen/internal/tests/const_array_length/input.go, mockgen/internal/tests/const_array_length/mock.go, mockgen/parse.go, mockgen/parse_test.go
=> fix: Support array parsing with length using binary expression and parenthesis

gomock/call.go, gomock/controller_test.go
In my https://github.com/golang/mock/pull/589, I missed to add the skip line in switch case.
=> Fix: missing ignore Fatal in SetArg function

gomock/call.go, gomock/call_test.go
Addresses https://github.com/golang/mock/issues/600
=> Don't error out for variadic functions in Do/DoReturn

gomock/controller.go, gomock/doc.go
=> add some docs on default TestReporter behavior

.gitignore, mockgen/internal/tests/mock_in_test_package/mock_test.go, mockgen/mockgen.go
When running mockgen with the output option this checks if the existing file content already exists and skips writing if there is nothing to change.
This will help reduce i/o when changing lots of files, but also reduce the re-indexing triggering in IDEs.
Solves #604
=> Skip rewriting output files if unchanged
